name: Rust MSRV

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MSRV
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.81.0
            override: true
            components: rustfmt, clippy

      # `cargo check` command here will use installed `MSRV`
      # as it is set as an "override" for current directory

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
